#!/usr/bin/env bash
# SPDX-License-Identifier: GPL-3.0-or-later
set -Eeuo pipefail
readonly APP_VERSION="1.0.0"
readonly CADDY_CONFIG="${CADDY_CONFIG:-/etc/caddy/Caddyfile}"
readonly CADDY_SITE_DIR="${CADDY_SITE_DIR:-/etc/caddy/conf.d}"
readonly CADDY_WEB_ROOT="${CADDY_WEB_ROOT:-/var/www/v2ray-manager}"
readonly NODES_DIR="${V2M_NODES_DIR:-/etc/xray/nodes}"
readonly BACKUP_DIR="${CADDY_BACKUP_DIR:-/var/backups/caddy-manager}"
readonly CONFIG_FILE="${V2M_XRAY_CONFIG:-/etc/xray/config.json}"
readonly CADDY_PORTFOLIO_REPO="0157Martin/v2ray-portfolio-page"
readonly CADDY_RESUME_REPO="0157Martin/v2ray-resume-page"

red() { printf '\033[31m%s\033[0m\n' "$*"; }
green() { printf '\033[32m%s\033[0m\n' "$*"; }
yellow() { printf '\033[33m%s\033[0m\n' "$*"; }
step() { printf '\033[33m%s\033[0m  %s\n' "$(date +%H:%M:%S)" "$*"; }
die() { red "错误：$*" >&2; exit 1; }
require_root() { [[ ${EUID:-$(id -u)} -eq 0 ]] || die '请使用 root 运行。'; }
valid_port() { [[ $1 =~ ^[0-9]+$ ]] && (( 10#$1 >= 1 && 10#$1 <= 65535 )); }
valid_server_name() { [[ $1 =~ ^([A-Za-z0-9]([A-Za-z0-9-]{0,61}[A-Za-z0-9])?\.)+[A-Za-z]{2,63}$ ]]; }
valid_transport_path() { [[ $1 == /* && $1 != *' '* && $1 != *//* && $1 != *\\* ]]; }
profile_supports_caddy_route() { [[ ${1:-${PROFILE:-}} == vless-tls-xhttp || ${1:-${PROFILE:-}} == vless-ws-tls || ${1:-${PROFILE:-}} == vmess-ws-tls || ${1:-${PROFILE:-}} == trojan-ws-tls ]]; }
check_caddy_renewal_compatibility() {
  local file
  [[ -d /etc/letsencrypt/renewal ]] || return 0
  for file in /etc/letsencrypt/renewal/*.conf; do
    [[ -f $file ]] || continue
    grep -Eq '^[[:space:]]*authenticator[[:space:]]*=[[:space:]]*standalone([[:space:]]|$)' "$file" || continue
    red "拒绝占用 TCP 80：$file 仍使用 Certbot standalone 续期。" >&2
    return 1
  done
}
check_caddy_activation_compatibility() { systemctl is-active --quiet caddy && return 0; check_caddy_renewal_compatibility; }
open_local_firewall_port() {
  local port=$1
  if command -v ufw >/dev/null 2>&1 && ufw status 2>/dev/null | grep -q '^Status: active'; then ufw allow "$port/tcp" >/dev/null; fi
  if command -v firewall-cmd >/dev/null 2>&1 && firewall-cmd --state >/dev/null 2>&1; then
    firewall-cmd --permanent --add-port="$port/tcp" >/dev/null
    firewall-cmd --reload >/dev/null
  fi
}

valid_caddy_upstream() {
  local port
  if [[ $1 =~ ^(127\.0\.0\.1|localhost):([0-9]+)$ ]]; then
    port=${BASH_REMATCH[2]}
  elif [[ $1 =~ ^\[::1\]:([0-9]+)$ ]]; then
    port=${BASH_REMATCH[1]}
  else
    return 1
  fi
  valid_port "$port"
}

render_caddy_site() {
  local mode=$1 domain=$2 upstream=${3:-} destination=$4 path=${5:-}
  valid_server_name "$domain" || return 1
  case "$mode" in
    static)
      cat > "$destination" <<EOF
$domain {
	root * $CADDY_WEB_ROOT/$domain
	encode zstd gzip
	file_server
}
EOF
      ;;
    reverse)
      valid_caddy_upstream "$upstream" || return 1
      cat > "$destination" <<EOF
$domain {
	encode zstd gzip
	reverse_proxy $upstream
}
EOF
      ;;
    xray)
      render_caddy_xray_site "$domain" "$upstream" "$destination" "$path"
      ;;
    *) return 1 ;;
  esac
}

# Render every eligible local XHTTP/WS inbound for this domain into one Caddy
# site. This avoids replacing an existing path route when a second inbound is
# added for the same HTTPS domain.
render_caddy_xray_site() {
  local domain=$1 upstream=$2 destination=$3 path=$4 node_dir=${CADDY_NODE_DIR_OVERRIDE:-$NODES_DIR}
  local node_file PROFILE SERVER_NAME PORT PATH_VALUE route_upstream route_path route_profile existing index=0
  local -a route_paths=() route_upstreams=() route_profiles=()
  declare -A seen_paths=()
  valid_caddy_upstream "$upstream" || return 1
  valid_transport_path "$path" || return 1

  route_paths+=("$path")
  route_upstreams+=("$upstream")
  route_profiles+=("")
  seen_paths["$path"]=$upstream

  if [[ -d $node_dir ]]; then
    for node_file in "$node_dir"/*.env; do
      [[ -f $node_file ]] || continue
      PROFILE=''; SERVER_NAME=''; PORT=''; PATH_VALUE=''
      # Node files are generated by this script with mode 0600.
      # shellcheck disable=SC1090
      . "$node_file"
      profile_supports_caddy_route "$PROFILE" || continue
      [[ $SERVER_NAME == "$domain" ]] || continue
      if ! valid_port "$PORT" || ! valid_transport_path "$PATH_VALUE"; then
        continue
      fi
      route_upstream="127.0.0.1:$PORT"
      route_path=$PATH_VALUE
      route_profile=$PROFILE
      existing=${seen_paths[$route_path]:-}
      if [[ -n $existing ]]; then
        [[ $existing == "$route_upstream" ]] || {
          red "同一 Caddy 路径 $route_path 对应多个 Xray 后端，拒绝覆盖。" >&2
          return 1
        }
        for index in "${!route_paths[@]}"; do
          if [[ ${route_paths[$index]} == "$route_path" && ${route_upstreams[$index]} == "$route_upstream" ]]; then
            route_profiles[index]=$route_profile
          fi
        done
        continue
      fi
      route_paths+=("$route_path")
      route_upstreams+=("$route_upstream")
      route_profiles+=("$route_profile")
      seen_paths["$route_path"]=$route_upstream
    done
  fi

  {
    printf '%s {\n' "$domain"
    for index in "${!route_paths[@]}"; do
      printf '\t@xray_%s path %s %s/*\n' "$index" "${route_paths[$index]}" "${route_paths[$index]}"
      if [[ ${route_profiles[$index]} == vless-tls-xhttp ]]; then
        printf '\treverse_proxy @xray_%s h2c://%s {\n' "$index" "${route_upstreams[$index]}"
        printf '\t\tflush_interval -1\n\t\ttransport http {\n\t\t\tversions h2c\n\t\t}\n\t}\n'
      else
        printf '\treverse_proxy @xray_%s https://%s {\n' "$index" "${route_upstreams[$index]}"
        printf '\t\tflush_interval -1\n\t\ttransport http {\n\t\t\ttls_server_name %s\n\t\t}\n\t}\n' "$domain"
      fi
    done
    printf '\troot * %s/%s\n\tencode zstd gzip\n\tfile_server\n}\n' "$CADDY_WEB_ROOT" "$domain"
  } > "$destination"
}

caddy_ports_available() {
  local port listeners
  if [[ -r $CONFIG_FILE ]] && jq -e 'any(.inbounds[]?; .port == 80 or .port == 443)' "$CONFIG_FILE" >/dev/null; then
    red "Xray 当前占用 TCP 80 或 443；标准 Caddy 无法与其共享端口。请先修改对应入站端口。" >&2
    return 1
  fi
  for port in 80 443; do
    listeners=$(ss -H -lntp "sport = :$port" 2>/dev/null || true)
    [[ -z $listeners || $listeners == *caddy* ]] || {
      red "TCP $port 已被其他服务占用，不会停止或覆盖该服务：" >&2
      printf '%s\n' "$listeners" >&2
      return 1
    }
  done
}

install_caddy() (
  local temporary
  command -v caddy >/dev/null 2>&1 && return 0
  check_caddy_renewal_compatibility || return 1
  caddy_ports_available || return 1
  step "安装 Caddy"
  apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y \
    debian-keyring debian-archive-keyring apt-transport-https curl gnupg || return 1
  temporary=$(mktemp -d) || return 1
  trap 'rm -rf -- "$temporary"' EXIT
  curl --fail --show-error --location --retry 3 \
    https://dl.cloudsmith.io/public/caddy/stable/gpg.key -o "$temporary/caddy.gpg.key" || return 1
  curl --fail --show-error --location --retry 3 \
    https://dl.cloudsmith.io/public/caddy/stable/debian.deb.txt -o "$temporary/caddy-stable.list" || return 1
  grep -Eq '^deb ' "$temporary/caddy-stable.list" || { red "Caddy 软件源内容无效。" >&2; return 1; }
  gpg --batch --yes --dearmor --output "$temporary/caddy-stable-archive-keyring.gpg" \
    "$temporary/caddy.gpg.key" || return 1
  install -m 644 "$temporary/caddy-stable-archive-keyring.gpg" \
    /usr/share/keyrings/caddy-stable-archive-keyring.gpg
  install -m 644 "$temporary/caddy-stable.list" /etc/apt/sources.list.d/caddy-stable.list
  apt-get update || return 1
  DEBIAN_FRONTEND=noninteractive apt-get install -y caddy || {
    red "无法从系统软件仓库安装 Caddy。" >&2
    return 1
  }
  command -v caddy >/dev/null 2>&1 || { red "Caddy 安装后仍不可执行。" >&2; return 1; }
)

ensure_caddy_import() {
  local temporary backup
  install -d -m 755 "$CADDY_SITE_DIR"
  if [[ ! -e $CADDY_CONFIG ]]; then
    printf 'import %s/*.caddy\n' "$CADDY_SITE_DIR" > "$CADDY_CONFIG"
    chmod 644 "$CADDY_CONFIG"
    return
  fi
  grep -Fqx "import $CADDY_SITE_DIR/*.caddy" "$CADDY_CONFIG" && return
  install -d -m 700 "$BACKUP_DIR"
  backup="$BACKUP_DIR/Caddyfile.$(date -u +%Y%m%dT%H%M%SZ)"
  cp -p "$CADDY_CONFIG" "$backup" || return 1
  temporary=$(mktemp "${CADDY_CONFIG}.XXXXXX") || return 1
  if cp -p "$CADDY_CONFIG" "$temporary" &&
     printf '\nimport %s/*.caddy\n' "$CADDY_SITE_DIR" >> "$temporary" &&
     mv -f "$temporary" "$CADDY_CONFIG"; then
    return
  fi
  rm -f -- "$temporary"
  return 1
}

render_caddy_placeholder_page() {
  local domain=$1 destination=$2
  valid_server_name "$domain" || return 1
  cat > "$destination" <<EOF
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="robots" content="noindex,nofollow">
  <title>Service available</title>
  <style>
    :root{color-scheme:light dark}*{box-sizing:border-box}body{margin:0;min-height:100vh;display:grid;place-items:center;background:#0b1220;color:#dbeafe;font:16px/1.6 system-ui,sans-serif}main{width:min(92%,560px);padding:40px;border:1px solid #24324a;border-radius:18px;background:#111b2e;box-shadow:0 24px 70px #0006}h1{margin:0 0 12px;font-size:1.7rem}p{margin:0;color:#94a3b8}code{color:#7dd3fc}
  </style>
</head>
<body><main><h1>Service available</h1><p>The HTTPS endpoint for <code>$domain</code> is online.</p></main></body>
</html>
EOF
}

landing_page_path() {
  valid_server_name "$1" || return 1
  printf '%s/%s/index.html' "$CADDY_WEB_ROOT" "$1"
}

install_caddy_placeholder_page() {
  local domain=$1 root page temporary
  valid_server_name "$domain" || return 1
  root="$CADDY_WEB_ROOT/$domain"
  page="$root/index.html"
  [[ ! -e $page ]] || return 0
  temporary=$(mktemp) || return 1
  if ! render_caddy_placeholder_page "$domain" "$temporary" ||
     ! install -d -m 755 "$root" ||
     ! install -m 644 "$temporary" "$page" ||
     ! chown caddy:caddy "$root" "$page"; then
    rm -f -- "$temporary" "$page"
    red '通用占位页写入失败。' >&2
    return 1
  fi
  rm -f -- "$temporary"
}

ensure_caddy_landing_page() {
  local page
  page=$(landing_page_path "$1") || return 1
  [[ -e $page ]] || install_caddy_placeholder_page "$1"
}

deploy_caddy_page() (
  set -Eeuo pipefail
  local domain=$1 template=${2:-portfolio} repository revision api base manifest path checksum
  local root stage backup=''
  valid_server_name "$domain" || { red '网页域名无效。' >&2; return 1; }
  case "$template" in
    portfolio) repository=$CADDY_PORTFOLIO_REPO ;;
    resume) repository=$CADDY_RESUME_REPO ;;
    default) repository='' ;;
    *) red '网页类型必须是 portfolio、resume 或 default。' >&2; return 1 ;;
  esac
  install -d -m 755 "$CADDY_WEB_ROOT" || return 1
  root="$CADDY_WEB_ROOT/$domain"
  stage=$(mktemp -d "$CADDY_WEB_ROOT/.page.XXXXXX") || return 1
  trap '[[ -z ${stage:-} ]] || rm -rf -- "$stage"' EXIT

  if [[ $template == default ]]; then
    render_caddy_placeholder_page "$domain" "$stage/index.html" || return 1
  else
    if ! command -v curl >/dev/null || ! command -v jq >/dev/null || ! command -v sha256sum >/dev/null; then
      red '安装可选网页需要 curl、jq 和 sha256sum。' >&2
      return 1
    fi
    api="https://api.github.com/repos/$repository/commits/main"
    revision=${V2M_CADDY_PAGE_REF:-}
    if [[ -z $revision ]]; then
      revision=$(curl --fail --silent --show-error --location --retry 3 --connect-timeout 15 --max-time 60 "$api" | jq -r '.sha') || return 1
    fi
    [[ $revision =~ ^[0-9a-f]{40}$ ]] || { red '无法取得网页模板的固定提交。' >&2; return 1; }
    base="https://raw.githubusercontent.com/$repository/$revision/dist"
    manifest="$stage/deploy-manifest.json"
    curl --fail --silent --show-error --location --retry 3 --connect-timeout 15 --max-time 120 \
      "$base/deploy-manifest.json" -o "$manifest" || return 1
    jq -e '.version == 1 and (.files | type == "array" and length > 0) and all(.files[]; (.path | type == "string" and test("^(index\\.html|site-config\\.json|favicon\\.svg|icons\\.svg|assets/[A-Za-z0-9._-]+)$")) and (.sha256 | type == "string" and test("^[0-9a-f]{64}$"))) and any(.files[]; .path == "index.html")' "$manifest" >/dev/null || {
      red '网页模板部署清单无效。' >&2
      return 1
    }
    while IFS=$'\t' read -r path checksum; do
      path=${path%$'\r'}; checksum=${checksum%$'\r'}
      mkdir -p "$stage/$(dirname "$path")" || return 1
      curl --fail --silent --show-error --location --retry 3 --connect-timeout 15 --max-time 120 \
        "$base/$path" -o "$stage/$path" || return 1
      [[ $(sha256sum "$stage/$path" | awk '{print $1}') == "$checksum" ]] || {
        red "网页文件校验失败：$path" >&2
        return 1
      }
    done < <(jq -r '.files[] | [.path, .sha256] | @tsv' "$manifest")
    rm -f -- "$manifest"
  fi

  jq -n --arg template "$template" --arg domain "$domain" --arg revision "${revision:-built-in}" \
    '{version:1,template:$template,domain:$domain,revision:$revision}' > "$stage/site-config.json" || return 1
  chown -R caddy:caddy "$stage" || return 1
  if [[ -e $root ]]; then
    backup="$CADDY_WEB_ROOT/.previous.$(date +%s).$RANDOM"
    mv -- "$root" "$backup" || return 1
  fi
  if ! mv -- "$stage" "$root"; then
    [[ -z $backup ]] || mv -- "$backup" "$root" || true
    red '网页发布失败，已恢复原网页。' >&2
    return 1
  fi
  stage=''
  [[ -z $backup ]] || rm -rf -- "$backup"
  green "可选网页已部署：https://$domain（$template）"
)

configure_caddy_site() {
  local mode=$1 domain=$2 upstream=${3:-} path=${4:-} target temporary previous='' had_previous=0
  valid_server_name "$domain" || { red "请输入有效完整域名。" >&2; return 1; }
  [[ $mode != reverse ]] || valid_caddy_upstream "$upstream" || {
    red "反向代理后端仅支持本机地址，例如 127.0.0.1:8080、localhost:3000 或 [::1]:8080。" >&2
    return 1
  }
  if [[ $mode == xray ]]; then
    valid_caddy_upstream "$upstream" || { red "Xray 后端仅支持本机地址。" >&2; return 1; }
    valid_transport_path "$path" || { red "Xray 传输路径无效，必须以 / 开头且不能包含空格。" >&2; return 1; }
  fi
  check_caddy_activation_compatibility || return 1
  caddy_ports_available || return 1
  install_caddy || return 1
  ensure_caddy_import || { red "无法安全更新 Caddyfile import。" >&2; return 1; }
  getent ahosts "$domain" >/dev/null 2>&1 || yellow "域名当前无法解析；Caddy 自动申请证书前请先配置 DNS。"
  target="$CADDY_SITE_DIR/$domain.caddy"
  temporary=$(mktemp "$CADDY_SITE_DIR/.${domain}.XXXXXX") || return 1
  render_caddy_site "$mode" "$domain" "$upstream" "$temporary" "$path" || { rm -f -- "$temporary"; return 1; }
  if [[ -e $target ]]; then
    previous=$(mktemp "$CADDY_SITE_DIR/.previous.XXXXXX") || return 1
    cp -p "$target" "$previous" || return 1
    had_previous=1
  fi
  install -m 644 -o root -g root "$temporary" "$target" || return 1
  rm -f -- "$temporary"
  if ! caddy validate --config "$CADDY_CONFIG" --adapter caddyfile; then
    if (( had_previous )); then mv -f "$previous" "$target"; else rm -f -- "$target"; fi
    red "Caddy 配置校验失败，已恢复旧站点配置。" >&2
    return 1
  fi
  if [[ $mode == static || $mode == xray ]]; then
    if ! ensure_caddy_landing_page "$domain"; then
      if (( had_previous )); then mv -f "$previous" "$target"; else rm -f -- "$target"; fi
      red '网页准备失败，已恢复旧站点配置，未重载 Caddy。' >&2
      return 1
    fi
  fi
  open_local_firewall_port 80
  open_local_firewall_port 443
  if systemctl is-active --quiet caddy; then
    if ! systemctl reload caddy; then
      if (( had_previous )); then mv -f "$previous" "$target"; else rm -f -- "$target"; fi
      systemctl reload caddy || true
      red "Caddy reload 失败，已恢复旧站点配置。" >&2
      return 1
    fi
  else
    if ! systemctl enable --now caddy; then
      if (( had_previous )); then mv -f "$previous" "$target"; else rm -f -- "$target"; fi
      red "Caddy 启动失败，已恢复旧站点配置。" >&2
      return 1
    fi
  fi
  [[ -z $previous ]] || rm -f -- "$previous"
  green "Caddy 站点已启用：https://$domain"
}


verify_caddy() {
  command -v caddy >/dev/null 2>&1 || die 'Caddy 尚未安装。'
  caddy validate --config "$CADDY_CONFIG" --adapter caddyfile
  systemctl is-active --quiet caddy || die 'caddy.service 未运行。'
  green 'Caddy 安装、配置和服务验证通过。'
}
repair_caddy() { ensure_caddy_import; caddy validate --config "$CADDY_CONFIG" --adapter caddyfile; systemctl enable --now caddy; }
uninstall_caddy() {
  systemctl disable --now caddy >/dev/null 2>&1 || true
  if command -v apt-get >/dev/null 2>&1; then DEBIAN_FRONTEND=noninteractive apt-get remove -y caddy; fi
  rm -f /etc/apt/sources.list.d/caddy-stable.list /usr/share/keyrings/caddy-stable-archive-keyring.gpg
  yellow 'Caddy 软件已卸载；站点配置、证书和网页数据已保留。'
}
usage() { printf '%s\n' '用法：caddy-manager <install|verify|static|reverse|xray|page|status|log|repair|uninstall|version>'; }
main() {
  local action=${1:-status}
  case "$action" in version|help|-h|--help) ;; *) require_root ;; esac
  case "$action" in
    install) install_caddy; ensure_caddy_import; systemctl enable --now caddy; verify_caddy ;;
    verify|test) verify_caddy ;;
    static) [[ -n ${2:-} ]] || die '用法：caddy-manager static <域名>'; configure_caddy_site static "$2" ;;
    reverse) [[ -n ${2:-} && -n ${3:-} ]] || die '用法：caddy-manager reverse <域名> <本机地址:端口>'; configure_caddy_site reverse "$2" "$3" ;;
    xray) [[ -n ${2:-} && -n ${3:-} && -n ${4:-} ]] || die '用法：caddy-manager xray <域名> <本机地址:端口> <路径>'; configure_caddy_site xray "$2" "$3" "$4" ;;
    page) [[ -n ${2:-} ]] || die '用法：caddy-manager page <域名> [portfolio|resume|default]'; deploy_caddy_page "$2" "${3:-portfolio}" ;;
    status) systemctl --no-pager --full status caddy || true ;;
    log) journalctl -u caddy -n 100 --no-pager ;;
    repair) repair_caddy; verify_caddy ;;
    uninstall) uninstall_caddy ;;
    version) printf 'caddy-manager %s\n' "$APP_VERSION" ;;
    help|-h|--help) usage ;;
    *) usage; die "未知操作：$action" ;;
  esac
}
if [[ "${BASH_SOURCE[0]}" == "$0" ]]; then
  main "$@"
fi
